### ISSUE TITLE
Updated by is showing the person who created the Issue, not updated.

### ISSUE THREAD

**Issue by danhellem** [danhellem/github-actions-issue-to-work-item#103]
## Issue description
See issue #57 for example. That issue is created by someone in the community. When doing "GitHub Issue Updated by {user}" it is showing the user of the person who create that issue. 

## What is should be doing...

It needs to show the person who updated the issue.

[AB#5437](https://dev.azure.com/danhellem/56243fe6-2ed4-4398-acde-6a289bc1d89a/_workitems/edit/5437)

**Comment by rokeno** [comment]
I've done some digging, looking into index.js, dunno much about java scripts but i have not seen anything there. Oktokit is the one that triggers an authentication issue => 400
All i could find so far is:
```
Date: Tue, 29 Nov 2022 10:45:45 GMT
Server: Kestrel
Transfer-Encoding: chunked
WWW-Authenticate: Bearer
x-tfs-processid: 66239f0a-f1fe-4392-8e81-ce3345d175cc
activityid: d971657f-42cd-4c21-8ce5-9f0dc7c8908c
x-tfs-session: ab1307f0-a33b-45c5-8058-a68f203cfa5e
x-vss-e2eid: 03860721-e323-46fe-b010-2c6e74bdf170
x-vss-senderdeploymentid: c2cd0eb4-8d48-44ab-e222-1c53d7c4a971
x-tfs-serviceerror: The+user+%27System%3aPublicAccess%3baaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa%27+is+not+authorized+to+access+this+resource.
x-vss-s2stargetservice: 0000005A-0000-8888-8000-000000000000/visualstudio.com
X-Frame-Options: DENY

[2022-11-29 10:45:45Z INFO RSAFileKeyManager] Loading RSA key parameters from file /mnt/external1/gha/a01/.credentials_rsaparams
[2022-11-29 10:45:45Z INFO GitHubActionsService] AAD Correlation ID for this token request: Unknown
[2022-11-29 11:15:46Z INFO MessageListener] No message retrieved from session 'e7bc63f0-be57-4e63-8836-aa8458a5beea' within last 30 minutes.
[2022-11-29 11:40:47Z WARN GitHubActionsService] Authentication failed with status code 401.
```

I don't know what this is: `The+user+%27System%3aPublicAccess%3baaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa%27`
