### ISSUE TITLE
Cannot create task for User story when opened from dashboard

### ISSUE THREAD

**Issue by TomasDyntar** [danhellem/github-actions-issue-to-work-item#105]
When I open a User story from a dashboard (URL is .../_dashboards/dashboard/_guid_), the button "+ Add link" does nothing.
When I open the User story as such (URL is ../_workitems/edit/_number_), the button "+ Add link" works fine and allows creating a child task.

[AB#5469](https://dev.azure.com/danhellem/56243fe6-2ed4-4398-acde-6a289bc1d89a/_workitems/edit/5469)

**Comment by danhellem** [comment]
Sorry @TomasDyntar , not sure this has anything to do with this action :(
