### ISSUE TITLE
Sync Devops Work Items to Github

### ISSUE THREAD

**Issue by SBAurelien** [danhellem/github-actions-issue-to-work-item#110]
Hello,

Your Github Action that synchronizes github output to Devops Work item works great. 

I would like to know, if it would be easy for you to do also the reverse. That is to say when I create a Work Item, it creates it on Github. Either by event on Devops, or by a job on Github.

What do you think about it?

AB#6354

**Comment by danhellem** [comment]
@SBAurelien yeah it can be done, but it requires you to create a custom service that are triggered from web hook events. So it is a little more work.
