### ISSUE TITLE
Markdown tables in GitHub not rendered into HTML in ADO

### ISSUE THREAD

**Issue by AaronCrawfis** [danhellem/github-actions-issue-to-work-item#113]
## GitHub Issue

```markdown
# Header 1

Paragraph

## Header 2

| X | Y | Z |
|---|---|---|
| 1 | 2 | 3 |

`Code block`

```

## Rendered ADO Issue

![image](https://user-images.githubusercontent.com/54363786/191584164-2aeb315a-1562-436e-ab98-3db3f3abccd4.png)

AB#7520

**Comment by danhellem** [comment]
@AaronCrawfis I am using a 3rd party component that does the rendering. So I am guessing this is just not supported. Unless you want to pick it up and investigate further, i don't expect to try and solve this.

**Comment by AaronCrawfis** [comment]
> @AaronCrawfis I am using a 3rd party component that does the rendering. So I am guessing this is just not supported. Unless you want to pick it up and investigate further, i don't expect to try and solve this.

Came across this comment: https://github.com/showdownjs/showdown/issues/945#issuecomment-1205375626

Looks like we just need to add `new showdown.Converter({ tables: "true" });` to https://github.com/danhellem/github-actions-issue-to-work-item/blob/master/index.js#L147

Docs here: https://showdownjs.com/docs/available-options/#tables
