### ISSUE TITLE
Error "Field 'Closed Date' cannot be empty" in Azure Boards

### ISSUE THREAD

**Issue by tkalve** [danhellem/github-actions-issue-to-work-item#124]
When an issue is closed in Github, the associated WI in Azure Boards is also closed, but when I open the WI in Azure Boards, I get the error `"Field 'Closed Date' cannot be empty"`.

What is causing this, and can I fix it myself somehow?

![image](https://user-images.githubusercontent.com/123207/210249953-21a6b4ca-3d39-409f-956c-4ebffc441b31.png)

[AB#19488](https://dev.azure.com/danhellem/56243fe6-2ed4-4398-acde-6a289bc1d89a/_workitems/edit/19488)

**Comment by danhellem** [comment]
@tkalve what process template are you using in Azure DevOps (Scrum, Agile, CMMI, or Basic)? From the screen shot it looks like you are creating Task work item types from the action?

**Comment by tkalve** [comment]
> what process template are you using in Azure DevOps?

I am using "Agile baseline template", not sure if that is something special for my organization. I am not org admin.

> From the screen shot it looks like you are creating Task work item types from the action?

Yes, I am creating Task work items.

**Comment by danhellem** [comment]
@tkalve okay, not sure why you are having the issue and nobody is. But i will try and take a look in the next couple of weeks.
