### ISSUE TITLE
What can I do if software I need is removed or replaced with a newer version?

### ISSUE THREAD

**Issue by laxmankab** [danhellem/github-actions-issue-to-work-item#128]
We are using latest ubuntu version agent specification under microsoft hosted agents ,that comes with latest default version 3.9.0  .
However our project -Mule projects supports only 3.8.7 or previous versions but not 3.9.0 . 
So till now we were using ubuntu 18.04 since that comes with 3.8.8 maven by default .

Can you help to support the 3.8.7 or lower with latest ubuntu version(22.04).

[AB#50055](https://dev.azure.com/danhellem/56243fe6-2ed4-4398-acde-6a289bc1d89a/_workitems/edit/50055)

**Comment by danhellem** [comment]
Sorry, not even sure how this is related to this repo. Closing this issue :(
