### ISSUE TITLE
Task is not creating as type "Bug" if passing ado_wit value as "bug"

### ISSUE THREAD

**Issue by rupinSec** [danhellem/github-actions-issue-to-work-item#129]
I would like to use this action to create ADO task type as **BUG** if I provide the ado_wit as "**bug**", but it is creating them as issue. 
<img width="525" alt="Screenshot 2023-03-21 at 5 58 03 PM" src="https://user-images.githubusercontent.com/44662963/226605989-756742ac-1247-49cf-80c7-bc08c78a30f4.png">

Here is the code snippet of this workflow
<jobs:
  create_issues:
    runs-on: ubuntu-latest
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@v2.0
        env:
          ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
          github_token: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
          ado_organization: ""
          ado_project: ""
          ado_new_state: "To Do"
          ado_active_state: "Doing"
          ado_close_state: "Done"
          ado_bypassrules: true
          log_level: 100
        if: contains(github.event.issue.labels.*.name, 'bug')
        with:
          ado_wit: "Bug"
      - uses: danhellem/github-actions-issue-to-work-item@v2.0
        env:
          ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
          github_token: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
          ado_organization: ""
          ado_project: ""
          ado_new_state: "To Do"
          ado_active_state: "Doing"
          ado_close_state: "Done"
          ado_bypassrules: true
          log_level: 100
        if: "!contains(github.event.issue.labels.*.name, 'bug')"
        with:
          ado_wit: "Issue">
[AB#50129](https://dev.azure.com/danhellem/56243fe6-2ed4-4398-acde-6a289bc1d89a/_workitems/edit/50129)

**Comment by danhellem** [comment]
If i had to guess, I suspect you are not using the if statements right. It also depends on when the labels event is fired. As I remember, you should create the issue first, save it, then add the label. If add the labels first, then save, the events are out of order.

**Comment by rupinSec** [comment]
The action starts working after I upgraded it to version v2.1.
