### ISSUE TITLE
[Question] can be used to link a work item to a user story?

### ISSUE THREAD

**Issue by dtcMLOps** [danhellem/github-actions-issue-to-work-item#131]
Hi @danhellem,

greetings.

I was wondering if this action can be used to link a work item to a user story.

[AB#50989](https://dev.azure.com/danhellem/56243fe6-2ed4-4398-acde-6a289bc1d89a/_workitems/edit/50989)

**Comment by danhellem** [comment]
hello @dtcMLOps,

Not sure I understand the question. A user story is a work item. This is action is used to link Issues to any kind of work item (user story, bug, etc.)

**Comment by dtcMLOps** [comment]
@danhellem  

A user story is not a work item (task item).

My question is if this action can achieve this connection

![Screenshot from 2023-05-18 13-24-41](https://github.com/danhellem/github-actions-issue-to-work-item/assets/115469901/f7e5ee2f-2ccb-405d-a759-a286bdeeca8d)

**Comment by danhellem** [comment]
Work item = any kind of item. So yes, a User Story is a Work Item and can be used. In fact I believe it is the default in Readme.md

**Comment by dtcMLOps** [comment]
@danhellem I think I have not made myself well understood. A user story can have a task item associated with it. My question is if I choose the option `ad_wit: "Task Item"` is there any option to link that task item (that is created on ADO) to a user story that was already created from ADO.

For example:

A user creates a user story call:` As SE I want a backend service` in the ADO portal.

Then a work item: user story is created.

Now from the github repository project, I open a new issue call: Feature request to add a backend module (something like that) and then, the action will create a task item in the ADO portal. This task item is created in the backlog.

Can I link that task item that I have created using the Issue Template from my repository with the User story that was already created in the ADO portal?
