### ISSUE TITLE
[feature request] output command is deprecated

### ISSUE THREAD

**Issue by dtcMLOps** [danhellem/github-actions-issue-to-work-item#133]
The output command is deprecated.

![Screenshot from 2023-05-25 13-33-51](https://github.com/danhellem/github-actions-issue-to-work-item/assets/115469901/b6f53330-606d-467c-922a-891434385ad9)

[AB#51051](https://dev.azure.com/danhellem/56243fe6-2ed4-4398-acde-6a289bc1d89a/_workitems/edit/51051)

**Comment by danhellem** [comment]
@dtcMLOps feel free to update and create a PR
