### ISSUE TITLE
[feature request] assigned work item

### ISSUE THREAD

**Issue by dtcMLOps** [danhellem/github-actions-issue-to-work-item#134]
Hi @danhellem,

would be great to have a parameter to assign the work item to the same user that opens the issue or pull request.

[AB#52492](https://dev.azure.com/danhellem/56243fe6-2ed4-4398-acde-6a289bc1d89a/_workitems/edit/52492)

**Comment by danhellem** [comment]
@dtcMLOps how would you do this when the identities between GitHub and Azure Boards are not the same?

**Comment by dtcMLOps** [comment]
Hi @danhellem actually I was thinking something like:

assigned: "myuser@gmail.com" or with the user id from azure devops. For my side I can create logic in the workflow to map the github user to specific email, but it would be great to have some input parameter in the action to assigne this to a user in ADO

**Comment by danhellem** [comment]
@dtcMLOps it don't think it is something I am going to put in the action. You can always fork and add your own custom logic. Closing this issue.
