### ISSUE TITLE
[Question] Are we syncing the 'Area Path' and 'Iteration Path' fields on 'Update' event?

### ISSUE THREAD

**Issue by RajeevPentyala** [danhellem/github-actions-issue-to-work-item#139]
@danhellem First of all thanks for this solution and it helped me a lot. Looks like the 'Iteration Path' field of Azure DevOps item is not being updated when I update the GitHub issue.

**Steps to reproduce :**

- Configure the GitHub Action as below
_steps:
      - uses: danhellem/github-actions-issue-to-work-item@master
        env:
          ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
          github_token: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
          ado_organization: "adoOrg"
          ado_project: "adoProject"
          ado_area_path: "adoOrg\\Path1"
          ado_iteration_path: "adoOrg\\Iteration1"  
          ado_wit: "User Story"
          ado_new_state: "New"
          ado_active_state: "Active"
          ado_close_state: "Resolved"
          ado_bypassrules: true
          log_level: 100_

- Create a new GitHub issue "Test Issue" and the issue successfully synced to Azure Devops.
- Now change the GitHub Action YAML as below. 
_steps:
      - uses: danhellem/github-actions-issue-to-work-item@master
        env:
          ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
          github_token: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
          ado_organization: "adoOrg"
          ado_project: "adoProject"
          ado_area_path: "adoOrg\\Path**2**"
          ado_iteration_path: "adoOrg\\Iteration**2**"  
          ado_wit: "User Story"
          ado_new_state: "New"
          ado_active_state: "Active"
          ado_close_state: "Resolved"
          ado_bypassrules: true
          log_level: 100_

- Notice that I changed the 'ado_area_path' and 'ado_iteration_path' fields to "adoOrg\\Path**2**" and "adoOrg\\Iteration**2**".
- Go to GitHub and update (i.e., Change 'Title' field) the GitHub issue we created previously.
- Now Sync happened and 'Title' field changed in Azure DevOps item but not the 'Area Path' and 'Iteration Path'.

Is this the expected behavior or am I missing something?

[AB#72460](https://dev.azure.com/danhellem/56243fe6-2ed4-4398-acde-6a289bc1d89a/_workitems/edit/72460)

**Comment by danhellem** [comment]
There is no sync, we just create a work item from the issue with the information that is defined in the Action at that time. We don't attempt to make updates back to the work items based on the area path or iteration path defined in the Action.

This is by design
