### ISSUE TITLE
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20

### ISSUE THREAD

**Issue by PRijnbeek** [danhellem/github-actions-issue-to-work-item#141]
The current workflow will not run due to deprecated Node.js can this be updated.

**Comment by RolfMoleman** [comment]
any updates on this at all?

**Comment by danhellem** [comment]
I will get it updated in the next week or two

**Comment by danhellem** [comment]
This issue is resolved in the main branch. Can you test it before I release an update?
