### ISSUE TITLE
Use tags on issue to create work item types

### ISSUE THREAD

**Issue by danhellem** [danhellem/github-actions-issue-to-work-item#16]
create an issue with the tag "Epic" or "Bug". Use that tag to create the work item type in Azure Boards

[AB#5152](https://dev.azure.com/danhellem/9e4ade6f-32de-4a10-9926-8821c4d1673a/_workitems/edit/5152)

**Comment by dan-miller** [comment]
Would this also handle changing the work item type if the tag is changed? For example if something we initially thought was a Bug is actually a User Story or Feature, it would be great if the tag change would cause the work item type to change.

**Comment by danhellem** [comment]
@dan-miller I like the suggestion!

**Comment by danhellem** [comment]
@dan-miller i am going to close this issue. Too much complexity here.
