### ISSUE TITLE
Bugs with Richtext will be created with plain text.

### ISSUE THREAD

**Issue by SBajonczak** [danhellem/github-actions-issue-to-work-item#37]
When I create a Bug with Richtext (images and formatted text). 
This will not correctly transfered. 

The complete input will be created as plaintext. 
Maybe it will be possible to get the Richtext body from Github to AzureDevops?

[AB#296](https://dev.azure.com/privatepreview/5136ae2e-ad01-4fa4-b7e9-7550b8cdd2c3/_workitems/edit/296)

**Comment by danhellem** [comment]
@SBajonczak are you referring to the description or discussion?

**Comment by SBajonczak** [comment]
Hi I speak about the description.

Gesendet von Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by danhellem** [comment]
@SBajonczak the problem with this is that Azure Boards using HTML and GitHub uses markdown. So the translation is going to be difficult. I am am going to mark this as "Enhancement" and see if it continues to come up. It would be a decent chunk of work to try and go fix.

**Comment by AaronCrawfis** [comment]
Would also love to see this, as we use Markdown in our GitHub issues. Would be cool to plug in a markdown renderer like https://github.com/markdown-it/markdown-it into the flow to automatically render the HTML and then paste that as the DevOps work item description.

**Comment by danhellem** [comment]
@AaronCrawfis  feel free to contribute your suggestion. Sadly I have moved on to a new team and not actively adding new features to this right now.

**Comment by danhellem** [comment]
@AaronCrawfis FYI, I am going to pick this back up and convert the markdown to HTML so that it renders nicely in the work item form.

**Comment by danhellem** [comment]
This is resolved in #102. Please take a look at the PR and test it out for feedback
