### ISSUE TITLE
Iteration Path

### ISSUE THREAD

**Issue by sheldonhull** [danhellem/github-actions-issue-to-work-item#40]
Is it possible to set iteration path?
Right now i have `team/active` and this means the issues are hidden from site, as it sets to `team` only on the iteration, not the default team iteration for the backlog. 

AB#5277

[AB#419](https://dev.azure.com/privatepreview/5136ae2e-ad01-4fa4-b7e9-7550b8cdd2c3/_workitems/edit/419)

**Comment by danhellem** [comment]
@sheldonhull iteration paths change too often. How would you set the path when the work item is created without having to edit the YAML every time? use @Current?

**Comment by sheldonhull** [comment]
Yes, @CurrentIteration is what I was thinking, or at least allowing it to be set. 
in my case we have 

```
devops
 -- active
       ---  sprints
-- archive
      --- archivedsprints
```

The default is `devops/active` as the backlog iteration for the team to ensure the archived content doesn't clutter up reports and all. I would like be able to provide that OR `@CurrentIteration` for example. The current iteration changes often, but there is often a default iteration for the backlog level and the sprints under that.

**Comment by danhellem** [comment]
@sheldonhull I appreciate the request but I think i am going to keep it as is for now. Feel free to fork and use as you see fit for your own needs

**Comment by sheldonhull** [comment]
@danhellem follow-up on this. If there is a multi-team project, which I believe is a common practice in larger orgs, this means I can't ensure it shows up on a backlog board. It will just show up in a list, but not on the default backlog.

Had trouble the last attempt, so will revisit soon. Here's my main question. 

Is it as simple as adding a new entry here:

https://github.com/danhellem/github-actions-issue-to-work-item/blob/6eff9634a3e42d565e2c66f396d0612e900093ec/index.js#L162-L169

Would I basically add the following? If acceptable, could I provide this as a Pull Request rather than maintaining a separate action since this would be useful to others using AZ Boards in a similar manner?

```javascript
	// if area path is not empty, set it
	if (vm.env.iterationPath != "") {
		patchDocument.push({
			op: "add",
			path: "/fields/System. IterationPath",
			value: vm.env.iterationPath,
		});
	}
```

Cheers

**Comment by danhellem** [comment]
@sheldonhull assigning to an area path is already in action now. I don't have plans to add a archived area path. If you want to use that, then you will need to run that on your own action.

https://github.com/danhellem/github-actions-issue-to-work-item/blob/master/index.js#L163

**Comment by sheldonhull** [comment]
https://github.com/sheldonhull/github-actions-issue-to-work-item

Sorry, I meant iteration. This is a standard setting for a team to assign as the iteration path can be different for every team in a project. Right now it doesn't get set. 

I am ready to give you a PR with IterationPath as an input for your review if you willing to consider that. Would like others to be able to use and not maintain a seperate copy for a normal azure boards input if possible. Otherwise I'll not submit if that's what you want. Cheers!

**Comment by danhellem** [comment]
@sheldonhull i would support a default iteration path

**Comment by sheldonhull** [comment]
I'm testing now and once I get it working I'll submit. thank you!

**Comment by sheldonhull** [comment]
I'm trying to get it to work, but getting this error. I'm probably doing something silly but not seeing it. The area path is correctly set to 

```
 {
    op: 'add',
    path: '/fields/System.AreaPath',
    value: 'devops/site-reliability'
  },
```

The error is below. Is there some escaping issue or something else relevant you think?

EDIT: WHOOPS. It's in the main readme. 

> ado_area_path: To set a specific area path you want your work items created in. If providing a full qualified path such as area\sub_area, then be sure to use the format of: ado_area_path: "area\\area" to avoid parsing failures.



```
Error: TF401347: Invalid tree name given for work item -1, field 'System.AreaPath'.
    at RestClient.<anonymous> (/home/runner/work/_actions/sheldonhull/github-actions-issue-to-work-item/master/node_modules/typed-rest-client/RestClient.js:202:31)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/sheldonhull/github-actions-issue-to-work-item/master/node_modules/typed-rest-client/RestClient.js:6:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  statusCode: 400,
  result: {
    '$id': '1',
    innerException: null,
    message: "TF401347: Invalid tree name given for work item -1, field 'System.AreaPath'.",
    typeName: 'Microsoft.TeamFoundation.WorkItemTracking.Server.WorkItemFieldInvalidTreeNameException, Microsoft.TeamFoundation.WorkItemTracking.Server',
    typeKey: 'WorkItemFieldInvalidTreeNameException',
    errorCode: 600171,
    eventId: 3200
  }
```

**Comment by sheldonhull** [comment]
Ok,it's working. I had single quotes as well instead of double quotes. 
Let me know if this is acceptable. This should put in the correct iteration path now. I feel like a javascript master now :-)
