### ISSUE TITLE
Existing issues do not sync

### ISSUE THREAD

**Issue by dan-miller** [danhellem/github-actions-issue-to-work-item#42]
We have many issues in our organization's repositories that we'd really like to sync with Azure Boards, but I want to avoid manually creating work items for all of them. 

It appears that the workflow simply ignores existing issues that are not already linked to Azure Boards work items, unless I am missing something.

AB#5279

**Comment by danhellem** [comment]
Hey Dan, 

Yeah it using the #mention in the title of the work item to sync. Not the link.
