### ISSUE TITLE
Create an issue on dependabot and security alerts

### ISSUE THREAD

**Issue by danhellem** [danhellem/github-actions-issue-to-work-item#55]
create a work item in azure boards for when a dependabot or security alert happens

[AB#378](https://dev.azure.com/privatepreview/5136ae2e-ad01-4fa4-b7e9-7550b8cdd2c3/_workitems/edit/378)

**Comment by Grenston** [comment]
Hey I was just thinking. Dependabot has the capability to automatically raise a pull request in github, and you already have an action to create a work item in Azure Boards when a pr is raised. This way you will be able to track dependency alerts too.

**Comment by danhellem** [comment]
Closing this out, not going to add this enhancement anytime soon
