### ISSUE TITLE
Azure DevOps to GitHub sync

### ISSUE THREAD

**Issue by Mr-PatKing** [danhellem/github-actions-issue-to-work-item#58]
If an issue is created in GitHub and synced to Azure DevOps, do you know if there is a way to update the Issue when a change is made to the synced item in AZDO?

[AB#415](https://dev.azure.com/privatepreview/5136ae2e-ad01-4fa4-b7e9-7550b8cdd2c3/_workitems/edit/415)

**Comment by danhellem** [comment]
not currently. You would need to use web hooks and rest api's to push the data back from ADO to GitHub.

This is one of the downsides to this action. It's really only a one way sync :(
