### ISSUE TITLE
Random error on execution

### ISSUE THREAD

**Issue by Msanzdelrio** [danhellem/github-actions-issue-to-work-item#61]
I am having the following error when trying to execute the action:
![image](https://user-images.githubusercontent.com/37813342/101660316-53537700-3a47-11eb-95ce-ae29f3021f43.png)

Action configuration is:

    - uses: danhellem/github-actions-issue-to-work-item@master
      env:     
        ado_token: '${{ secrets.ADO_PAT }}'
        github_token: '${{ secrets.REPO_ACCESS_TOKEN }}'
        ado_organization: 'Make-Github-Real'
        ado_project: 'Make-Github-Real'
        ado_wit: 'Bug' 
        ado_new_state: 'New'
        ado_close_state: 'Closed'
        ado_active_state: 'Active'  
        ado_bypassrules: true

[AB#705](https://dev.azure.com/privatepreview/5136ae2e-ad01-4fa4-b7e9-7550b8cdd2c3/_workitems/edit/705)

**Comment by danhellem** [comment]
This is most likely caused by an invalid token, toke scope, or organization name

I have not been able to pinpoint catching those errors better. So if you have some ideas feel free to create a PR

**Comment by Msanzdelrio** [comment]
Does the action accept dashes as part of the organization name? like: azure-devops-organization?

**Comment by danhellem** [comment]
yeah it should support dashes in the org name. But to be honest I have not tested that.

**Comment by Msanzdelrio** [comment]
@danhellem  do the organization/project need any special format? or is it just the name? I have testes with organizatiion/project with no special characters, just letters, but still its not working

**Comment by danhellem** [comment]
@Msanzdelrio yeah you just need the project name and org name. Check and make sure the Bug WIT is correct with those correct states. If you are still stuck, i am happy to debug with you if you can add me to your org/project for testing

**Comment by danhellem** [comment]
@Msanzdelrio did you get this figured out?

**Comment by Msanzdelrio** [comment]
Hi!

Yes I fixed it! Not sure how, I recreated every PAT and it worked! Thank
you!! 😊

**Comment by danhellem** [comment]
@Msanzdelrio great. That is usually the case or sometimes a typo in the org or project. Glad you got it working!
