### ISSUE TITLE
Allow specification of alternative to "Description" field

### ISSUE THREAD

**Issue by Blackbaud-DanMiller** [danhellem/github-actions-issue-to-work-item#63]
Our Bug work items do not have a Description field (we have Repro Steps and System Info). It appears that this workflow assumes that the target work item uses the System.Description field, so we wind up not getting the bodies of the issues copied to our Bugs.

[AB#708](https://dev.azure.com/privatepreview/5136ae2e-ad01-4fa4-b7e9-7550b8cdd2c3/_workitems/edit/708)

**Comment by danhellem** [comment]
@Blackbaud-DanMiller okay. I will see if I can add the system info field to the patch document even if the field does not exist. If that works i will go ahead and fix this. If it it throws an error then i will probably punt it and ask you to go fork the code and update it to fit your needs.
