### ISSUE TITLE
How can we use this action without Azure Boards App in our local GHE Server.

### ISSUE THREAD

**Issue by praveenapuri** [danhellem/github-actions-issue-to-work-item#73]
We are using GitHub Enterprise server and don't have Marketplace to install the Azure Boards App. Is there any way we use this action without Azure Boards App installed.

Appreciate your time.

[AB#718](https://dev.azure.com/privatepreview/5136ae2e-ad01-4fa4-b7e9-7550b8cdd2c3/_workitems/edit/718)

**Comment by danhellem** [comment]
i don't know if GHE supports access tokens. So i don't think it is going to be supported :(

**Comment by praveenapuri** [comment]
Yes, it does support access tokens
