### ISSUE TITLE
reflect github username in Azure board on sync with github actions issue

### ISSUE THREAD

**Issue by sandeepmalu** [danhellem/github-actions-issue-to-work-item#74]
[AB#719](https://dev.azure.com/privatepreview/5136ae2e-ad01-4fa4-b7e9-7550b8cdd2c3/_workitems/edit/719)

**Comment by danhellem** [comment]
@sandeepmalu can you add some details to the description? I will go ahead and look at this over the next few days.

**Comment by sandeepmalu** [comment]
When an issue is created on github by any "user" in an organization repository, It should reflect that "user_name" on all attributes of Azure board issue irrespective of whose AZURE_PAT is used.

**Comment by danhellem** [comment]
@sandeepmalu go ahead and get the latest and give it a try. If the bypassrules are turned on, then it will use the sender.user.login value for the person who created the issue
