### ISSUE TITLE
Failed Sync

### ISSUE THREAD

**Issue by dainnielnoahlopez** [danhellem/github-actions-issue-to-work-item#76]
![image](https://user-images.githubusercontent.com/79292516/116513318-f83df600-a8fb-11eb-9e18-00dbe5fd057c.png)

Can you tell me what to do here? I'm no good at coding, Sorry

[AB#720](https://dev.azure.com/privatepreview/5136ae2e-ad01-4fa4-b7e9-7550b8cdd2c3/_workitems/edit/720)

**Comment by danhellem** [comment]
@dainnielnoahlopez check and make sure your env variables are correct. Are you using User Stories or PBI's?
