### ISSUE TITLE
401 when a new issue is create in GH

### ISSUE THREAD

**Issue by ylr-research** [danhellem/github-actions-issue-to-work-item#78]
@danhellem I followed the steps as per the configuration guide and I just got this error. Should be something easy but I can't find out what it is.

![image](https://user-images.githubusercontent.com/63487874/116840415-b59e4700-aba3-11eb-8040-a330bd177bbf.png)

[AB#722](https://dev.azure.com/privatepreview/5136ae2e-ad01-4fa4-b7e9-7550b8cdd2c3/_workitems/edit/722)

**Comment by ylr-research** [comment]
Never mind, I had an old token

**Comment by danhellem** [comment]
yeah these are usually because of a bad token or typo in the org or project name
