### ISSUE TITLE
Sync only particular labels

### ISSUE THREAD

**Issue by philcart** [danhellem/github-actions-issue-to-work-item#80]
Hi

Just wondering if this could be setup to only sync specific labels with ADO?

Cheers
Phil

[AB#723](https://dev.azure.com/privatepreview/5136ae2e-ad01-4fa4-b7e9-7550b8cdd2c3/_workitems/edit/723)

**Comment by danhellem** [comment]
@philcart as in, only create work items where label = "Foo"?

**Comment by philcart** [comment]
@danhellem yeh, that's essentially what we're looking to do. The GitHub issues are currently being used as discussion points, often with no development/technical impact. Once the discussion reaches a certain point a DevOps work item is manually created.

**Comment by danhellem** [comment]
@philcart okay, yeah you could fork the code and add some logic to check for specific labels before syncing to ADO.

You may also want to look into GitHub's new discussion feature. It was designed to address your scenario above
